language: cpp
dist: trusty

env:
  global:
    - BAZEL_VERSION=0.24.1

notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - BAZEL_OS=linux
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
      env:
        - BAZEL_OS=linux
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
    - eval "${MATRIX_EVAL}"
    - wget https://github.com/bazelbuild/bazel/releases/download/${BAZEL_VERSION}/bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh
    - chmod +x bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh
    - ./bazel-${BAZEL_VERSION}-installer-${BAZEL_OS}-x86_64.sh --user

script:
  - bazel build ...
  - bazel test ...
