language: cpp
dist: trusty
script: script/travis/test.sh
notifications:
  email: false

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - BAZEL_OS=linux
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - libstdc++-7-dev
      env:
        - BAZEL_OS=linux
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
    - eval "${MATRIX_EVAL}"
